name: Dependency Review

on:
  pull_request:
    branches:
      - problem_d
    paths:
      - 'src/artifacts/problem_d/problem_d_backend/package.json'
      - 'src/artifacts/problem_d/problem_d_backend/package-lock.json'
      - 'src/artifacts/problem_d/problem_d_frontend/package.json'
      - 'src/artifacts/problem_d/problem_d_frontend/package-lock.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
